### PR TITLE
Initial bsd-port porting work in progress

### PR DESCRIPTION
**Pull request by bsdkurt**
I am able to complete a full build on OpenBSD and the resulting jdk is able to be used for natively bootstraping the next build.

My build process to get an initial native jdk build is as follows:

My git repo is located at the following path: `/home/truk/jdk/openjdk-jdk11u`. I have exported this path with nfs and mounted it on an Ubuntu xenial node at the exact same path. I setup a password-less ssh key so can ssh from my OpenBSD node to xenial without a password, then I installed AdoptOpenJDK/openjdk-jdk11u on xenial to act as the bootstrap jdk.

```
cd /home/truk/jdk/openjdk-jdk11u
bash configure \
  --with-boot-jdk=/home/truk/jdk/boot-jdk11 \
  --with-fontconfig-include=/usr/X11R6/include \
  --with-debug-level=release \
  --with-toolchain-type=clang \
  --disable-ccache \
  --disable-javac-server \
  --with-zlib=system \
  --with-jobs=6

gmake LOG=debug images
```
Where /home/truk/jdk/boot-jdk11 is a directory that looks like this:
```
# find /home/truk/jdk/boot-jdk11
/home/truk/jdk/boot-jdk11
/home/truk/jdk/boot-jdk11/bin
/home/truk/jdk/boot-jdk11/bin/jar
/home/truk/jdk/boot-jdk11/bin/jarsigner
/home/truk/jdk/boot-jdk11/bin/java
/home/truk/jdk/boot-jdk11/bin/javac
/home/truk/jdk/boot-jdk11/bin/javadoc
```
and jar, jarsigner, java, javac and javadoc are all hard linked to this script:
```
#!/usr/local/bin/bash
progname=`basename $0`
exec ssh kurt@xenial -- /home/kurt/jdk-11.0.2+9/bin/$progname "${@@Q}"
```

It is important that the export path match the mount point on the linux node so that everything linesup for the remote bootstrap commands.

### CODE REVIEW

**Comment by battleblow** [comment]
Thanks so much for working on this Kurt!

I'll merge this change and give it a try on FreeBSD.

**Comment by bsdkurt** [comment]
If you want to skip the serviceability agent for the first build, look at make/autoconf/jdk-options.m4 for INCLUDE_SA.

**Comment by battleblow** [comment]
I needed a couple of tweaks for FreeBSD, but it is compiling now (and is self hosting).  If you want to review, here are the commits:

https://github.com/battleblow/openjdk-jdk11u/commit/55d8b8bfe423cb758346937bf197bac78887c16c
https://github.com/battleblow/openjdk-jdk11u/commit/53b534e3e2322e9af7c3730ed0ab6740dfc64c8a
https://github.com/battleblow/openjdk-jdk11u/commit/3d3772219ffefbed93426007c0af44555b424c4e
https://github.com/battleblow/openjdk-jdk11u/commit/0d8317692fda572c0fd2d9eb63c5f522a62c1d42
https://github.com/battleblow/openjdk-jdk11u/commit/1fba8a09a7f2a7ff7a3b99b774e3fd7b2144308f

The first two there are the ones I'd most appreciate you taking a look at.

**Comment by bsdkurt** [comment]
I reviewed the commits and made one comment on the first one in the commit itself. The rest look good to me and work well here. Thanks for fixing the preprocessor check for OpenBSD.

**Comment by bsdkurt** [comment]
I have an uncomitted diff for `src/java.base/bsd/native/libjava/ProcessHandleImpl_bsd.c` that I haven't had time to debug. This file is for *BSD only (not Apple). I copied Apple's version and tried to come up with a supportable *BSD by using #defines. It builds for me but doesn't yet work so needs some debugging. I figured I'd share it in case I don't find the time to get this working right. I was testing it by removing the `--disable-javac-server` configure arg.
```
diff --git a/src/java.base/bsd/native/libjava/ProcessHandleImpl_bsd.c b/src/java.base/bsd/native/libjava/ProcessHandleImpl_bsd.c
index e2419443e9..93424d9d5f 100644
--- a/src/java.base/bsd/native/libjava/ProcessHandleImpl_bsd.c
+++ b/src/java.base/bsd/native/libjava/ProcessHandleImpl_bsd.c
@@ -37,8 +37,23 @@
 #include <unistd.h>
 #include <string.h>
 
+#include <sys/types.h>
 #include <sys/sysctl.h>
 
+#if defined(__OpenBSD__)
+#define KI_PID         p_pid
+#define KI_PPID        p_ppid
+#define KI_UID         p_uid
+#define KI_START_SEC   p_ustart_sec
+#define KI_START_USEC  p_ustart_usec
+#elif defined(__FreeBSD__)
+#define KI_PID         ki_pid
+#define KI_PPID        ki_ppid
+#define KI_UID         ki_uid
+#define KI_START_SEC   ki_start.tv_sec
+#define KI_START_USEC  ki_start.tv_usec
+#endif
+
 /**
  * Implementation of native ProcessHandleImpl functions for BSD's.
  * See ProcessHandleImpl_unix.c for more details.
@@ -58,7 +73,6 @@ void os_initNative(JNIEnv *env, jclass clazz) {}
  */
 jint os_getChildren(JNIEnv *env, jlong jpid, jlongArray jarray,
                     jlongArray jparentArray, jlongArray jstimesArray) {
-#ifdef __APPLE__
     jlong* pids = NULL;
     jlong* ppids = NULL;
     jlong* stimes = NULL;
@@ -137,18 +151,18 @@ jint os_getChildren(JNIEnv *env, jlong jpid, jlongArray jarray,
 
         // Process each entry in the buffer
         for (i = nentries; --i >= 0; ++kp) {
-            if (pid == 0 || kp->kp_eproc.e_ppid == pid) {
+            if (pid == 0 || kp->KI_PPID == pid) {
                 if (count < arraySize) {

                     // Only store if it fits
-                    pids[count] = (jlong) kp->kp_proc.p_pid;
+                    pids[count] = (jlong) kp->KI_PID;
                     if (ppids != NULL) {
                         // Store the parentPid
-                        ppids[count] = (jlong) kp->kp_eproc.e_ppid;
+                        ppids[count] = (jlong) kp->KI_PPID;
                     }
                     if (stimes != NULL) {
                         // Store the process start time
-                        jlong startTime = kp->kp_proc.p_starttime.tv_sec * 1000 +
-                                          kp->kp_proc.p_starttime.tv_usec / 1000;
+                        jlong startTime = kp->KI_START_SEC * 1000 +
+                                          kp->KI_START_USEC / 1000;
                         stimes[count] = startTime;
                     }
                 }
@@ -170,11 +184,6 @@ jint os_getChildren(JNIEnv *env, jlong jpid, jlongArray jarray,
     free(buffer);
     // If more pids than array had size for; count will be greater than array size
     return count;
-#else
-    JNU_ThrowByName(env, "java/lang/UnsupportedOperationException",
-            "unsupported option");
-    return -1;
-#endif
 }
 
 /**
@@ -185,7 +194,6 @@ jint os_getChildren(JNIEnv *env, jlong jpid, jlongArray jarray,
  */
 pid_t os_getParentPidAndTimings(JNIEnv *env, pid_t jpid,
                                 jlong *totalTime, jlong *startTime) {
-#ifdef __APPLE__
     const pid_t pid = (pid_t) jpid;
     pid_t ppid = -1;
     struct kinfo_proc kp;
@@ -199,14 +207,19 @@ pid_t os_getParentPidAndTimings(JNIEnv *env, pid_t jpid,
             "java/lang/RuntimeException", "sysctl failed");
         return -1;
     }
-    if (bufSize > 0 && kp.kp_proc.p_pid == pid) {
-        *startTime = (jlong) (kp.kp_proc.p_starttime.tv_sec * 1000 +

-                              kp.kp_proc.p_starttime.tv_usec / 1000);
-        ppid = kp.kp_eproc.e_ppid;
+    if (bufSize > 0 && kp.KI_PID == pid) {
+        *startTime = (jlong) (kp.KI_START_SEC * 1000 +
+                              kp.KI_START_USEC / 1000);
+        ppid = kp.KI_PPID;
     }
 
     // Get cputime if for current process
     if (pid == getpid()) {
+#ifdef __OpenBSD__
+        jlong microsecs = kp.p_uutime_sec * 1000 * 1000 + kp.p_uutime_usec +
+            kp.p_ustime_sec * 1000 * 1000 + kp.p_ustime_usec;
+        *totalTime = microsecs * 1000;
+#else
         struct rusage usage;
         if (getrusage(RUSAGE_SELF, &usage) == 0) {
           jlong microsecs =
@@ -214,17 +227,12 @@ pid_t os_getParentPidAndTimings(JNIEnv *env, pid_t jpid,
               usage.ru_stime.tv_sec * 1000 * 1000 + usage.ru_stime.tv_usec;
           *totalTime = microsecs * 1000;
         }
+#endif
     }
 
     return ppid;
-#else
-    JNU_ThrowByName(env, "java/lang/UnsupportedOperationException",
-            "unsupported option");
-    return -1;
-#endif
 }
 
-#ifdef __APPLE__
 /**
  * Return the uid of a process or -1 on error
  */
@@ -236,21 +244,19 @@ static uid_t getUID(pid_t pid) {
     int mib[4] = {CTL_KERN, KERN_PROC, KERN_PROC_PID, pid};
 
     if (sysctl(mib, 4, &kp, &bufSize, NULL, 0) == 0) {
-        if (bufSize > 0 && kp.kp_proc.p_pid == pid) {
-            return kp.kp_eproc.e_ucred.cr_uid;

+        if (bufSize > 0 && kp.KI_PID == pid) {
+            return kp.KI_UID;
         }
     }
     return (uid_t)-1;
 }
-#endif
 
 /**
  * Retrieve the command and arguments for the process and store them
  * into the Info object.
  */
 void os_getCmdlineAndUserInfo(JNIEnv *env, jobject jinfo, pid_t pid) {
-#ifdef __APPLE__
-    int mib[3], maxargs, nargs, i;
+    int mib[4], maxargs, nargs, i;
     size_t size;
     char *args, *cp, *sp, *np;
 
@@ -280,8 +286,9 @@ void os_getCmdlineAndUserInfo(JNIEnv *env, jobject jinfo, pid_t pid) {
         char *argsEnd;
         jstring cmdexe = NULL;
 
+#if defined(__OpenBSD__)
         mib[0] = CTL_KERN;
-        mib[1] = KERN_PROCARGS2;
+        mib[1] = KERN_PROC_ARGS;
         mib[2] = pid;
         size = (size_t) maxargs;
         if (sysctl(mib, 3, args, &size, NULL, 0) == -1) {
@@ -291,6 +298,20 @@ void os_getCmdlineAndUserInfo(JNIEnv *env, jobject jinfo, pid_t pid) {
             }
             break;
         }
+#elif defined(__FreeBSD__)
+        mib[0] = CTL_KERN;
+        mib[1] = KERN_PROC;
+        mib[2] = KERN_PROC_ARGS;
+        mib[3] = pid;
+        size = (size_t) maxargs;
+        if (sysctl(mib, 4, args, &size, NULL, 0) == -1) {
+            if (errno != EINVAL) {
+                JNU_ThrowByNameWithLastError(env,

+                    "java/lang/RuntimeException", "sysctl failed");
+            }
+            break;
+        }
+#endif
         memcpy(&nargs, args, sizeof(nargs));
 
         cp = &args[sizeof(nargs)];      // Strings start after nargs
@@ -312,9 +333,5 @@ void os_getCmdlineAndUserInfo(JNIEnv *env, jobject jinfo, pid_t pid) {
     } while (0);
     // Free the arg buffer
     free(args);
-#else
-    JNU_ThrowByName(env, "java/lang/UnsupportedOperationException",
-            "unsupported option");
-#endif
 }
 
```

**Comment by battleblow** [comment]
Thanks Kurt.  I plan to start taking a look at support for some of the features we have disabled next week.  This is one I'll take a look at.

**Pull request merged**
