### PR TITLE
OpenBSD ProcessHandle and networking changes

### PR DESCRIPTION
**Pull request by bsdkurt**
With these changes javac server works and the port for OpenBSD is ready initial release.

### CODE REVIEW

**Comment by bsdkurt** [comment]
Thanks Greg! Could you do a test build on FreeBSD to confirm I didn't break `os_getCmdlineAndUserInfo` when I cleaned up some unused variables?

Also when working on this file I noticed that `unix_fillArgArray` appears to skip the first argument and the code in the !OpenBSD case for `os_getCmdlineAndUserInfo` skips off the executable path already. If I read the code correctly, the first argument after the executable will be missed in the result.

**Comment by battleblow** [comment]
Hi Kurt, the initial build succeeds.  I'll try a build with it as the bootstrap, but I don't expect any problems.

Thanks for the pointer on ```unix_fillArgArray```, I'll write some tests for that and verify/fix.

**Comment by battleblow** [comment]
BTW, let me know if you'd like me to create a release for this so you can connect the OpenBSD port to it more easily.

**Comment by bsdkurt** [comment]
Thanks. At the moment I'm good with release 2 for the port. I have only a few patches and it's not a problem at all.

BTW, I'm really liking using github for bsd-port as compared to the mercurial + list setup at OpenJDK.

**Comment by battleblow** [comment]
Ok.  Releases are pretty easy though, so I hope to do them relatively frequently.

Yes, so far I'm pretty happy with how it's going with github.  I think I will even do future updates to OpenJDK8 (if there are any) on here.

**Pull request merged**
