### PR TITLE
Network interfaces report FreeBSD support.

### PR DESCRIPTION
**Pull request by devnexen**
The goal here was to reduce ifdef usage as possible while
Darwin and FreeBSD share the vast majority of the code.

### CODE REVIEW

**Comment by bsdkurt** [comment]
Off-topic:
I'd like to work on bringing in OpenBSD support soon and wanted to know if I should seek to reduce code duplication with Apple in the process or keep that separate and have Free/Net/Open share where possible? I was thinking along the lines of how it was done in:

https://github.com/battleblow/openjdk-jdk11u/blob/bsd-port/src/java.base/bsd/native/libjava/ProcessHandleImpl_bsd.c#L49

**Comment by devnexen** [comment]
Yes definitely this is the way to go, for example for all the work using kinfo_proc there might be the possiblity to reduce code specifics (albeit for example OpenBSD cannot get a process path etc ...).

**Comment by battleblow** [comment]
David, what testing have you done with this?  Are you looking at JFR recordings to verify this is working as expected?

**Comment by battleblow** [comment]
I think there are a couple of ways we could simplify how this code is structured, but without seeing how this will work on OpenBSD I think it would be premature to do so now.  Kurt, I support going with similar techniques to what was used in ProcessHandleImpl_bsd.c

**Comment by devnexen** [comment]
> David, what testing have you done with this? Are you looking at JFR recordings to verify this is working as expected?

That s a fair question, allowed me to find a little edge case.

**Comment by battleblow** [comment]
> > David, what testing have you done with this? Are you looking at JFR recordings to verify this is working as expected?
> 
> That s a fair question, allowed me to find a little edge case.

Thanks!  Could you please squash these commits together?  That makes it easier to track and cherry pick into the related trees (openjdk12u, corretto-11).

**Pull request merged**
